name: Build and publish distribution

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
        cibw-arch: [auto, aarch64]
        exclude:
          # Do not build wheel for linux-aarch64 temporarily
          - os: ubuntu-latest
            cibw-arch: aarch64
          - os: macos-latest
            cibw-arch: aarch64

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up QEMU
      if: runner.os == 'Linux'
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Install openblas
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt install libopenblas-dev
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install openblas
        fi
      shell: bash

    - name: Prepare CIBW_BUILD value
      id: prep_cibw
      shell: bash
      run: |
        PY_VERSION_INPUT="${{ matrix.python-version }}"
        PY_VERSION_NO_DOT="${PY_VERSION_INPUT//./}"
        echo "CIBW_BUILD_VAR=cp${PY_VERSION_NO_DOT}-*" >> $GITHUB_ENV

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.13.1
      env:
        CIBW_BUILD: ${{ env.CIBW_BUILD_VAR }}
        CIBW_ARCHS_LINUX: ${{ matrix.cibw-arch }}
        CIBW_ARCHS_MACOS: ${{ matrix.cibw-arch }}

    - name: Build sdist
      run: |
        pip install build
        python -m build . --sdist -o wheelhouse
      if: ${{ matrix.python-version == '3.11' && runner.os == 'Linux'  && matrix.cibw-arch == 'auto' }}

    - uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.os }}-py${{ matrix.python-version }}-${{ matrix.cibw-arch }}
        path: wheelhouse
        if-no-files-found: warn

  publish:
    name: Publish
    needs: [build_wheels]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
    environment: pypi
    permissions:
      id-token: write

    steps:
    - name: Download all wheel/sdist artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
